#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# Check for conventional commits
npx --no -- commitlint --edit ${1}

# Check for modifications to package.json
./check-package-json-commit.js "${1}"